# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
#    - go mod tidy
#    - go mod vendor
    - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
    - mips64
    - mips64le
    - mips
    - mipsle
  gomips:
    - hardfloat
    - softfloat
  ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - tap:
      owner: OpenIoTHub
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/IoTDevice/phicomm-r1-controler
    description: Phicomm R1 Controler
    test: |
      system "#{bin}/phicomm-r1-controler -v"
scoop:
  bucket:
    owner: OpenIoTHub
    name: scoop-bucket
  homepage:  https://github.com/IoTDevice/phicomm-r1-controler
  description: Phicomm R1 Controler
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    homepage:  https://github.com/IoTDevice/phicomm-r1-controler
    description: Phicomm R1 Controler
    maintainer: OpenIoTHub <newfarry@126.com>
    license: MIT
    vendor: phicomm-r1-controler
    formats:
      - deb
      - rpm
    scripts:
      preinstall: "scripts/install_remove/preinstall.sh"
      postinstall: "scripts/install_remove/postinstall.sh"
      preremove: "scripts/install_remove/preremove.sh"
      postremove: "scripts/install_remove/postremove.sh"
    contents:
      - src: systemd/**
        dst: /etc/systemd/system
      - src: phicomm-r1-controler.yaml
        dst: /etc/phicomm-r1-controler/phicomm-r1-controler.yaml
        type: config
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    summary: Phicomm R1 Controler.
    name: onvif
    description: |
      Phicomm R1 Controler
    grade: stable
#    confinement: classic
    publish: true
    apps:
      phicomm-r1-controler:
        plugs: ["network", "network-bind"]
        daemon: simple
        command: phicomm-r1-controler
dockers:
  - image_templates:
      - 'openiothub/phicomm-r1-controler:{{ .Tag }}'
      - 'openiothub/phicomm-r1-controler:v{{ .Major }}.{{ .Minor }}'
      - 'openiothub/phicomm-r1-controler:latest'
    dockerfile: Dockerfile
    binaries:
      - phicomm-r1-controler
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=com.github.actions.name={{.ProjectName}}"

    extra_files:
      - scripts/entrypoint.sh